spring.application.name: kafka-stream-poc
server.port: 8080

logging.level:
  org.springframework: INFO
  com.sunilbainsla: DEBUG

spring.cloud.stream.bindings:
  topic6Consumer-in-0:
    destination: topic6
    group: topic6-consumer-group-1
  topic7Consumer-in-0:
    destination: topic7
    group: topic7-consumer-group-1
spring.cloud.stream:
  function.definition: topic6Consumer;topic7Consumer
  kafka.streams:
    bindings:
      topic6Consumer-in-0.consumer.configuration.application.id: ${spring.application.name}-topic6Consumer
      topic7Consumer-in-0.consumer.configuration.application.id: ${spring.application.name}-topic7Consumer
    binder:
      configuration:
        commit.interval.ms: 1000
        processing.guarantee: exactly_once
        max.poll.interval.ms: 2147483647 # 300000
      deserializationExceptionHandler: logAndContinue