swagger: "2.0"

info:
  title: Replay utilities API
  version: 1.0.0

paths:
  /api/retry:
    post:
      summary: Create a retry
      description: Use this endpoint to perform retries.
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/retry'
      responses:
        '201':
          description: Resource created successfully
        '400':
          description: Bad request
  /api/reset:
    post:
      summary: Create a reset
      description: Use this endpoint to perform reset.
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: '#/definitions/reset'
      responses:
        '201':
          description: Resource created successfully
        '400':
          description: Bad request
definitions:
  reset:
    type: object
    properties:
      resetList:
        type: array
        items:
          $ref: '#/definitions/resetList'
  resetList:
    type: object
    properties:
      consumerGroup:
        type: string
      srcTopic:
        type: string
      topicDetails:
        type: array
        items:
          $ref: '#/definitions/resetTopicDetails'
    required:
      - consumerGroup
      - topicDetails
      - srcTopic
  resetTopicDetails:
    type: object
    properties:
      offset:
        type: string
      partition:
        type: string
    required:
      - offset
      - partition
  retry:
    type: object
    properties:
      source:
        type: string
    required:
      - source
    allOf:
      - properties:
          source:
            enum:
              - DB
          dbAttributes:
            $ref: '#/definitions/dbAttributes'
      - properties:
          source:
            enum:
              - KAFKA
          kafkaAttributes:
            $ref: '#/definitions/kafkaAttributes'

  dbAttributes:
    type: object
    properties:
      correlationid:
        type: string
      dbDetails:
        type: string
    required:
      - correlationid

  kafkaAttributes:
    type: object
    properties:
      replicationMode:
        type: string
    required:
      - replicationMode
    allOf:
      - properties:
          replicationMode:
            enum:
              - One
          replicationModeOne:
            $ref: '#/definitions/replicationModeOne'
      - properties:
          replicationMode:
            enum:
              - All
          replicationModeAll:
            $ref: '#/definitions/replicationModeAll'

  replicationModeOne:
    type: object
    properties:
      srcTopic:
        type: string
      destTopic:
        type: string
      partition:
        type: string
      offset:
        type: string
    required:
      - srcTopic
      - destTopic
      - partition
      - offset

  replicationModeAll:
    type: array
    items:
      $ref: '#/definitions/replicationModeAllItem'

  replicationModeAllItem:
    type: object
    properties:
      srcTopic:
        type: string
      destTopic:
        type: string
    required:
      - srcTopic
      - destTopic
